### ISSUE TITLE
ModuleNotFoundError: No module named 'whisperx.vads'

### ISSUE THREAD

**Issue by iedmrc** [m-bain/whisperX#1090]
[This](https://github.com/m-bain/whisperX/commit/3205436d5885c3d99052a85fa31e293eaff87215) commit causes the following error:

```
     import whisperx
   File "/usr/local/lib/python3.12/site-packages/whisperx/__init__.py", line 4, in <module>
     from .asr import load_model
   File "/usr/local/lib/python3.12/site-packages/whisperx/asr.py", line 16, in <module>
     from .vads import Vad, Silero, Pyannote
 ModuleNotFoundError: No module named 'whisperx.vads'
```

**Comment by xezpeleta** [comment]
Same issue here

**Comment by Barabazs** [comment]
This should be resolved now. Can you try again please?

**Comment by Barabazs** [comment]
@hexams Sorry about that... Can you try with the latest changes please?
The package discovery wasn't set up properly

**Comment by hexams** [comment]
> Sorry about that... Can you try with the latest changes please?
> The package discovery wasn't set up properly

it works!

**Comment by cczw2010** [comment]
still the same issue in : f10dbf6ab1717e84db7733df9c0b21658ee68f9b

**Comment by xezpeleta** [comment]
Fixed :)
