### ISSUE TITLE
Timestamp issue

### ISSUE THREAD

**Issue by Barabazs** [m-bain/whisperX#43]
I noticed that when I transcribe videos the subtitles aren't displayed anymore. Apparently the start and end timestamp are much closer together than before. I noticed this for all my new transcriptions.

This is a comparison between a transcription I did with the same settings in December vs now
red: old transcription
green: new transcription
```diff
--- <unnamed>
+++ <unnamed>
@@ -1,55 +1,55 @@
 WEBVTT
 
-00:06.854 --> 00:09.218
+00:06.854 --> 00:06.874
 REDACTED
 
-00:10.747 --> 00:10.990
+00:10.747 --> 00:10.869
 REDACTED
 
-01:30.038 --> 01:31.039
+01:30.038 --> 01:30.098
 REDACTED
 
-01:32.560 --> 01:36.980
+01:32.560 --> 01:32.600
 REDACTED
 
-01:37.100 --> 01:37.685
+01:37.100 --> 01:37.141
 REDACTED
 
-01:39.860 --> 01:42.014
+01:39.860 --> 01:39.900
 REDACTED
 
-01:42.960 --> 01:43.124
+01:42.960 --> 01:43.062
 REDACTED
 
-01:44.538 --> 01:44.620
+01:44.538 --> 01:44.559
 REDACTED
 
-01:45.820 --> 01:47.458
+01:45.820 --> 01:45.861
 REDACTED
 
-01:47.680 --> 01:49.620
+01:47.680 --> 01:47.741
 REDACTED
 
-01:49.660 --> 01:51.518
+01:49.660 --> 01:49.761
 REDACTED
 
-01:54.140 --> 01:57.878
+01:54.140 --> 01:54.301
 REDACTED
 
-01:58.400 --> 02:03.240
+01:58.400 --> 01:58.541
 REDACTED
 
-02:18.761 --> 02:20.514
+02:18.761 --> 02:18.781
 REDACTED
 
-02:21.280 --> 02:23.316
+02:21.280 --> 02:21.381
 REDACTED
 
-02:25.300 --> 02:27.217
+02:25.300 --> 02:25.361
 REDACTED
 
-02:27.600 --> 02:32.379
+02:27.600 --> 02:27.620
 REDACTED
 
-02:32.840 --> 02:34.756
+02:32.840 --> 02:32.921
 REDACTED

```

**Comment by Barabazs** [comment]
I checkout out older commits and re-ran my pipeline and I narrowed the problem down to this commit 286a2f2c14c159b6aa6fb96e1f1acff309d32714 .

**Comment by m-bain** [comment]
thanks for finding this, ok I have made this older (safe commit) the default branch. I work on these new logic / make sure its stable before release

**Comment by Barabazs** [comment]
I think you'll have to revert the stable branch to this commit: d395c21b8399cb2f29643a75f91469917cdbb991
The other commits still result in errors.

PS: is there any way to support you?

**Comment by m-bain** [comment]
Can you try recent commit on `main?` I think I fixed pandas logic now
@Barabazs do you mean with coding? Happy to merge pull requests and get help with improvements. Otherwise I added a buy-me-a-coffee to the readme :)

**Comment by arnavmehta7** [comment]
@m-bain Hey, After new fix in pandas logic, my code broke on whisperx
```
"/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/whisperx/alignment.py:294: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.\nTo preserve the previous behavior, use\n>>> .groupby(..., group_keys=False)\nTo adopt the future behavior and silence this warning, use\n>>> .groupby(..., group_keys=True)\nchar_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()\n"```

**Comment by m-bain** [comment]
@arnavmehta7 isn't that just a warning, not an error?

**Comment by Barabazs** [comment]
> Can you try recent commit on `main?` I think I fixed pandas logic now

I tried and I still get the same ultra short timestamps.

> @Barabazs do you mean with coding? Happy to merge pull requests and get help with improvements. Otherwise I added a buy-me-a-coffee to the readme :)

I'll send you a few :coffee: !

**Comment by m-bain** [comment]
@Barabazs thanks!

Ah I think I see the issue. 
https://github.com/m-bain/whisperX/commit/76f79f600a76fe2bd3d5387e4c468286005473fe
.min() where there should've been a .max()

**Comment by arnavmehta7** [comment]
@m-bain I don't remember, but it kinda i think broke the code. But it went fine after I switched to the stable branch.

**Comment by Barabazs** [comment]
> @Barabazs thanks!
> 
> Ah I think I see the issue. [76f79f6](https://github.com/m-bain/whisperX/commit/76f79f600a76fe2bd3d5387e4c468286005473fe) .min() where there should've been a .max()

Yeah, that fixed it. Thank you! :pray:
